;; Emacs alias names, for the Emacs preset (GitHub #263, epic E13; v0.8), not loaded by
;; default. These are the Emacs-style command names that used to live in the default
;; product's #:aliases lists, before docs/REPLAN.md §8 ("default-no-emacs") moved them
;; behind the opt-in preset so Windows and macOS users never meet Emacs vocabulary.
;;
;; Format: a list of (command-symbol "emacs-name" ...), one entry per built-in command
;; (rackmac/commands.rkt) that used to carry Emacs-style aliases. `command-symbol` is the
;; stable name registered with `define-command`/`register-command!` (see rackmac/command.rkt);
;; the strings are the Emacs names to re-register as aliases when the preset is enabled.
;;
;; Nothing in the default app requires or reads this file (tests/no-emacs-test.rkt checks
;; that). The v0.8 preset mechanism (E13.M1) reads it to restore these names.

((new-document "create buffer")
 (open-file "find-file")
 (quick-open "projectile")
 (save "save-buffer")
 (save-as "write-file")
 (close-tab "kill-buffer")
 (next-tab "next-tab" "other-buffer")
 (previous-tab "previous-tab")
 (reload-from-disk "revert-buffer")
 (set-line-endings "set-buffer-file-coding-system")
 (show-encoding "buffer-file-coding-system")
 (save-all "save-some-buffers")
 (print-document "print-buffer")
 (customize-with-code "init.el")
 (reload-init "load-file init")
 (list-extensions "list-packages")
 (quit "kill-emacs")
 (undo "undo-tree")
 (redo "undo-redo")
 (cut "kill-region" "kill")
 (copy "kill-ring-save")
 (paste "yank")
 (select-all "mark-whole-buffer")
 (select-line "mark line")
 (find "isearch-forward")
 (replace "query-replace" "replace-string")
 (find-next "isearch-repeat-forward")
 (find-previous "isearch-repeat-backward")
 (goto-line "goto-line")
 (toggle-comment "comment-dwim" "comment-region")
 (delete-line "kill-whole-line" "kill line")
 (move-line-up "transpose-lines")
 (move-line-down "transpose-lines")
 (indent-lines "indent-rigidly")
 (word-left "backward-word")
 (word-right "forward-word")
 (line-start "beginning-of-line")
 (line-end "end-of-line")
 (doc-start "beginning-of-buffer")
 (doc-end "end-of-buffer")
 (page-up "scroll-down-command")
 (page-down "scroll-up-command")
 (delete-word-back "backward-kill-word")
 (delete-word-forward "kill-word")
 (delete-to-line-start "backward-kill-line")
 (zoom-in "text-scale-increase")
 (zoom-out "text-scale-decrease")
 (zoom-reset "text-scale-adjust")
 (toggle-word-wrap "visual-line-mode" "truncate-lines")
 (toggle-toolbar "tool-bar-mode")
 (toggle-full-screen "toggle-frame-fullscreen")
 (toggle-theme "load-theme")
 (show-activity-log "view-echo-area-messages" "*Messages*")
 (command-palette "M-x" "execute-extended-command")
 (set-language "major mode" "set-language")
 (run-selection "eval-region" "eval-last-sexp")
 (run-document "run-document" "evaluate buffer")
 (describe-key "describe-key")
 (show-cheat-sheet "describe-bindings" "key map")
 (describe-command "describe-function" "apropos")
 (about "about-emacs"))
