#lang racket/base
;; Validates docs/roadmap.rktd and generates ROADMAP.md.   racket tools/roadmap.rkt
(require racket/list racket/string racket/file racket/match racket/runtime-path racket/format)
(provide load-roadmap validate flatten-issues render (struct-out iss))

(define-runtime-path data-path "../docs/roadmap.rktd")
(define-runtime-path out-path "../ROADMAP.md")

(define (load-roadmap) (call-with-input-file data-path read))

;; issue = (issue key title size status acceptance deps)
(struct iss (num key title size status accept deps epic milestone sub) #:transparent)

(define (flatten-issues rm)
  (define n 0)
  (for*/list ([e (in-list (filter (lambda (x) (eq? (car x) 'epic)) (cdr rm)))]
              [m (in-list (list-tail e 5))]                       ; epic, name, title, goal, design ref, then milestones
              [s (in-list (cdddr m))]
              [i (in-list (cdddr s))])
    (set! n (add1 n))
    (match i
      [(list 'issue key title size status accept deps)
       (iss n key title size status accept deps (cadr e) (cadr m) (cadr s))])))

(define (validate rm)
  (define is (flatten-issues rm))
  (define keys (map iss-key is))
  (define errs '())
  (define (err! fmt . a) (set! errs (cons (apply format fmt a) errs)))
  (let ([dup (check-duplicates keys)]) (when dup (err! "duplicate key ~a" dup)))
  (define ok (list->seteq* keys))
  (for ([i is])
    (unless (memq (iss-size i) '(S M L)) (err! "~a: bad size ~a" (iss-key i) (iss-size i)))
    (unless (memq (iss-status i) '(todo doing done icebox)) (err! "~a: bad status ~a" (iss-key i) (iss-status i)))
    (when (string=? (string-trim (iss-title i)) "") (err! "~a: empty title" (iss-key i)))
    (for ([d (iss-deps i)]) (unless (hash-ref ok d #f) (err! "~a: unknown dependency ~a" (iss-key i) d))))
  (reverse errs))

(define (list->seteq* l) (for/hasheq ([x l]) (values x #t)))

(define (status-box s) (case s [(done) "[x]"] [else "[ ]"]))
(define (tag s) (case s [(doing) " _(in progress)_"] [(icebox) " _(icebox)_"] [else ""]))

(define (render rm)
  (define is (flatten-issues rm))
  (define by-key (for/hasheq ([i is]) (values (iss-key i) i)))
  (define (id i) (format "RM-~a" (~r (iss-num i) #:min-width 3 #:pad-string "0")))
  (define (count pred l) (length (filter pred l)))
  (define out (open-output-string))
  (define (p . xs) (for ([x xs]) (display x out)) (newline out))
  (define epics (filter (lambda (x) (eq? (car x) 'epic)) (cdr rm)))
  (define releases (cdr (assq 'releases (cdr rm))))
  (p "# Rackmac roadmap")
  (p)
  (p "_Generated from `docs/roadmap.rktd` by `racket tools/roadmap.rkt`. Edit the data file, not this one._")
  (p)
  (p "Hierarchy: **epic > milestone > sub-milestone > issue**. Sizes: `S` under half a day, `M` one to two days, `L` three to five.")
  (p "Issues are tracked on GitHub: <https://github.com/marctjones/rackmac/issues>. Issue N there is roadmap item RM-N, GitHub")
  (p "milestones are the milestones below, and each epic has a tracking issue. **This file is the initial plan**, kept as an")
  (p "overview; from the first filing onward, GitHub is the source of truth for status. Issues added after the first")
  (p "filing (#240 onward: review findings, UI foundation; #265 onward: the 2026-09-25 re-plan's new work) exist only on GitHub.")
  (p)
  (p "**Re-plan (2026-09-25):** the Releases table below assigns one release per epic; `docs/REPLAN.md` section 7 moves some")
  (p "individual issues to a different release than their epic's row shows here. GitHub's per-issue `release:vX.Y` labels are")
  (p "the source of truth for an issue's release, not this table.")
  (p)
  (define active (filter (lambda (i) (not (eq? (iss-status i) 'icebox))) is))
  (p (format "**Progress:** ~a of ~a active issues done (~a in the icebox)."
             (count (lambda (i) (eq? (iss-status i) 'done)) active) (length active)
             (count (lambda (i) (eq? (iss-status i) 'icebox)) is)))
  (p)
  (p "## Releases")
  (p)
  (p "| Release | Theme | Epics | Done |")
  (p "|---|---|---|---|")
  (for ([r releases])
    (define es (third r))
    (define in (filter (lambda (i) (memq (iss-epic i) es)) active))
    (p (format "| ~a | ~a | ~a | ~a/~a |" (first r) (second r) (string-join (map symbol->string es) ", ")
               (count (lambda (i) (eq? (iss-status i) 'done)) in) (length in))))
  (p)
  (p "## Epics")
  (p)
  (p "| Epic | Title | Done |")
  (p "|---|---|---|")
  (for ([e epics])
    (define mine (filter (lambda (i) (eq? (iss-epic i) (cadr e))) is))
    (define act (filter (lambda (i) (not (eq? (iss-status i) 'icebox))) mine))
    (p (format "| ~a | ~a | ~a/~a |" (cadr e) (caddr e) (count (lambda (i) (eq? (iss-status i) 'done)) act) (length act))))
  (for ([e epics])
    (match-define (list* 'epic ename title goal ref milestones) e)
    (p)
    (p (format "## ~a: ~a" ename title))
    (p)
    (p (format "**Goal.** ~a  " goal))
    (p (format "**Design.** ~a" ref))
    (for ([m milestones])
      (match-define (list* 'milestone mname mtitle subs) m)
      (define mis (filter (lambda (i) (eq? (iss-milestone i) mname)) is))
      (p)
      (p (format "### ~a: ~a  (~a/~a)" mname mtitle
                 (count (lambda (i) (eq? (iss-status i) 'done)) mis) (length mis)))
      (for ([s subs])
        (match-define (list* 'sub sname stitle issues) s)
        (p)
        (p (format "#### ~a: ~a" sname stitle))
        (p)
        (for ([i (filter (lambda (i) (eq? (iss-sub i) sname)) is)])
          (define acc (filter (lambda (x) (not (string=? x ""))) (map string-trim (string-split (iss-accept i) "|"))))
          (define deps (map (lambda (k) (id (hash-ref by-key k))) (iss-deps i)))
          (p (format "- ~a **~a** ~a `~a`~a~a~a"
                     (status-box (iss-status i)) (id i) (iss-title i) (iss-size i) (tag (iss-status i))
                     (if (null? acc) "" (format " — _accept:_ ~a." (string-join acc "; ")))
                     (if (null? deps) "" (format " _Depends on: ~a._" (string-join deps ", "))))))))
    )
  (get-output-string out))

(module+ main
  (define rm (load-roadmap))
  (define errs (validate rm))
  (cond [(pair? errs) (for ([e errs]) (eprintf "roadmap error: ~a\n" e)) (exit 1)]
        [else (display-to-file (render rm) out-path #:exists 'truncate)
              (printf "wrote ~a (~a issues)\n" out-path (length (flatten-issues rm)))]))
