#lang racket/base
;; Vendors the Workbench icons Rackmac uses from the Skeptical Engineering design repository
;; into rackmac/ui/workbench-icons.rktd (docs/UI-DESIGN.md section 1.5).
;;   racket tools/workbench-icons.rkt [path/to/skepticalengineering-design]
;; The default path is the sibling checkout ../skepticalengineering-design. Only the outlined
;; ("filled") form of each icon is copied: it is the 1.5-unit stroke already expanded to shapes,
;; so the app fills it and never needs an SVG stroker.
(require racket/string racket/port racket/system racket/runtime-path json)
(provide mapping)

(define-runtime-path out-path "../rackmac/ui/workbench-icons.rktd")
(define-runtime-path default-source "../../skepticalengineering-design")

;; Rackmac icon name (what #:icon says) -> Workbench icon name.
(define mapping
  '(("activity" . "logbook-moth") ("arrow-down" . "arrow-down") ("arrow-up" . "arrow-up") ("book" . "book") ("calendar" . "calendar")
    ("check" . "check") ("checklist" . "checkbox") ("chevron-down" . "chevron-down") ("chevron-left" . "chevron-left")
    ("chevron-right" . "chevron-right") ("close" . "close") ("comment" . "chat") ("copy" . "copy") ("cut" . "cut")
    ("delete-line" . "trash") ("duplicate" . "plus") ("error" . "error") ("extensions" . "package")
    ("find" . "search") ("goto" . "flag") ("help" . "help") ("history" . "clock") ("indent" . "arrow-right")
    ("info" . "info") ("keyboard" . "keyboard") ("language" . "code") ("link" . "link") ("maximize" . "window") ("more" . "more")
    ("new" . "file-new") ("open" . "folder-open") ("outdent" . "arrow-left") ("palette" . "terminal")
    ("paste" . "paste") ("print" . "print") ("redo" . "redo") ("replace" . "sort") ("run" . "play")
    ("run-all" . "refresh") ("save" . "save") ("save-as" . "download") ("search" . "search")
    ("select-all" . "checkbox-checked") ("settings" . "settings") ("theme" . "moon") ("undo" . "undo")
    ("warning" . "warning") ("wrap" . "pilcrow-mark") ("x" . "close") ("zoom-in" . "zoom-in")
    ("zoom-out" . "zoom-out") ("zoom-reset" . "ruler")))

(define (source-commit dir)
  (define git (find-executable-path "git"))
  (or (and git (string-trim (with-output-to-string
                              (lambda () (system* git "-C" (path->string dir) "log" "-1" "--format=%h")))))
      "unknown"))

(define (main [dir default-source])
  (define icons
    (for/hash ([i (in-list (hash-ref (call-with-input-file (build-path dir "assets" "icons" "workbench-icons.json")
                                        read-json)
                                      'icons))])
      (values (hash-ref i 'name) (string-trim (hash-ref i 'filled)))))
  (call-with-output-file out-path #:exists 'truncate
    (lambda (o)
      (fprintf o ";; Generated by tools/workbench-icons.rkt from skepticalengineering-design ~a\n" (source-commit dir))
      (fprintf o ";; (assets/icons/workbench-icons.json). Do not edit: change the mapping in that tool and rerun it.\n")
      (fprintf o ";; Each entry: (rackmac-icon-name workbench-name outlined-path), the path on the 24-unit grid.\n(\n")
      (for ([m (in-list mapping)])
        (define d (hash-ref icons (cdr m) (lambda () (error 'workbench-icons "no Workbench icon ~s" (cdr m)))))
        (fprintf o " (~s ~s ~s)\n" (car m) (cdr m) d))
      (fprintf o ")\n")))
  (printf "wrote ~a icons to ~a\n" (length mapping) out-path))

(module+ main
  (define args (current-command-line-arguments))
  (if (> (vector-length args) 0) (main (string->path (vector-ref args 0))) (main)))
